
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 01 23:29:09 CST 2025
//----------------------------------------------------

package com.example.practica1_compi1.bknd.Parcer.Texto;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int BLACKED = 14;
  public static final int PLUS = 5;
  public static final int DECIMAL = 3;
  public static final int INITLIST = 17;
  public static final int ASTHERISK = 8;
  public static final int POTENCIA = 9;
  public static final int L_PAREN = 11;
  public static final int LETTER = 4;
  public static final int STRING = 13;
  public static final int R_PAREN = 10;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int DIVIDE = 7;
  public static final int MINUS = 6;
  public static final int DOT = 18;
  public static final int error = 1;
  public static final int ITALIC = 15;
  public static final int BLITALIC = 16;
  public static final int NUMERAL = 12;
}

