
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 02 02:40:30 CST 2025
//----------------------------------------------------

package com.example.practica1_compi1.bknd.Parcer.Codigo;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int MINUS = 6;
  public static final int DECIMAL = 3;
  public static final int DIVIDE = 7;
  public static final int POTENCIA = 9;
  public static final int LETTER = 4;
  public static final int R_PAREN = 10;
  public static final int ASTHERISK = 8;
  public static final int NUMBER = 2;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int FORMAT = 15;
  public static final int ASSING = 13;
  public static final int NUMERAL = 12;
  public static final int error = 1;
  public static final int PRINT = 14;
  public static final int L_PAREN = 11;
}

